apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-share
  namespace: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 225Gi

