apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: nfs
spec:
  type: NodePort
  selector:
    app: nfs-server
  ports:
  - name: nfs
    port: 2049
    targetPort: 2049
    nodePort: 30049
    protocol: TCP

